// Code generated by "stringer -type TokenType token/tokentype.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[COMMA-5]
	_ = x[DOT-6]
	_ = x[MINUS-7]
	_ = x[PLUS-8]
	_ = x[SEMICOLON-9]
	_ = x[SLASH-10]
	_ = x[STAR-11]
	_ = x[BANG-12]
	_ = x[BANG_EQUAL-13]
	_ = x[EQUAL-14]
	_ = x[EQUAL_EQUAL-15]
	_ = x[GREATER-16]
	_ = x[GREATER_EQUAL-17]
	_ = x[LESS-18]
	_ = x[LESS_EQUAL-19]
	_ = x[IDENTIFIER-20]
	_ = x[STRING-21]
	_ = x[NUMBER-22]
	_ = x[AND-23]
	_ = x[CLASS-24]
	_ = x[ELSE-25]
	_ = x[FALSE-26]
	_ = x[FUN-27]
	_ = x[FOR-28]
	_ = x[IF-29]
	_ = x[NIL-30]
	_ = x[OR-31]
	_ = x[PRINT-32]
	_ = x[RETURN-33]
	_ = x[SUPER-34]
	_ = x[THIS-35]
	_ = x[VAR-36]
	_ = x[WHILE-37]
	_ = x[TRUE-38]
	_ = x[EOF-39]
}

const _TokenType_name = "LEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTMINUSPLUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBERANDCLASSELSEFALSEFUNFORIFNILORPRINTRETURNSUPERTHISVARWHILETRUEEOF"

var _TokenType_index = [...]uint8{0, 10, 21, 31, 42, 47, 50, 55, 59, 68, 73, 77, 81, 91, 96, 107, 114, 127, 131, 141, 151, 157, 163, 166, 171, 175, 180, 183, 186, 188, 191, 193, 198, 204, 209, 213, 216, 221, 225, 228}

func (i TokenType) String() string {
	i -= 1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
